# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1
FROM python:3.11-slim

# Install dependencies for CairoSVG and Pillow
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      libcairo2 \
      libpango-1.0-0 \
      libpangocairo-1.0-0 \
      libxml2 \
      libjpeg-dev \
      zlib1g-dev \
      pkg-config \
      build-essential \
      libffi-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy source
COPY . /app

# Install Python dependencies and the MCP server
RUN pip install --no-cache-dir .

# Use the console script entrypoint
CMD ["mcp-chess"]
